### PR TITLE
Kiosk checkin page improvements

### PR DESCRIPTION
**Pull request by Jchuchla**
Modified checkin kiosk page to make banner consistent with other kiosk pages.  adjusted it to use the banner css classes.

### CODE REVIEW

**Comment by jeffpiazza** [comment]
Nice!  Definitely improves the look.

Better would probably be just calling make_banner, as a few other kiosk pages do.

The banner title changes when everyone's checked in -- "All Participants Have Checked In".  In that case, there probably needs to be a gap added between the make_banner and the full_page_center.

I'll merge the commit if you can make those changes, please.

**Comment by Jchuchla** [comment]
I made some additional changes to the layout.  Also fixed the layout of the flag page since it seemed like it should be tied to the same full_page_center class.

Does make_banner have the means to suppress the icons in the upper right?  Seems like those wouldn’t be desirable for a kiosk.

I’ll be honest.  I know very little about php and web development.  I’m learning a new language as I’m digging into this.

I pushed the changes up to my repo.

**Comment by jeffpiazza** [comment]
Yes, make_banner is preferred over hand-rolled divs.  You'll need a require_once('inc/banner.inc'); among the other require_once's, too.

To resolve the merge conflict, I think you'd need to sync your fork and then resolve conflicts locally.

I'd rather not expand the scope of this PR while it's still in progress.  Could you hold off on the flag page changes for now?

Also, could you please squash the commits together so there's just one to look at?
https://stackoverflow.com/questions/5667884/how-to-squash-commits-in-git-after-they-have-been-pushed

**Comment by Jchuchla** [comment]
I think the easiest thing to do here is just start over on a new branch with a new PR.  I’ll just revert my local branch to the current master and then reapply the changes on a new branch.  I’ll only include the two files related to the checkin page.  Then I’ll create another branch for the flag page adjustments and create a separate PR.  It’ll be dependent on the first PR though as it relies on the adjustments to the css for full page center.


--Jon Chuchla--

**Pull request closed without merging**
